workflows:
  octopals-ios-workflow:
    name: Native iOS Pipeline
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - mwazowsky
      vars:
        APPLE_KEY_ID: $APPLE_KEY_ID        # Key ID (10-character string)
        APPLE_ISSUER_ID: $APPLE_ISSUER_ID  # Issuer ID (UUID format)
        APPLE_PRIVATE_KEY: $APPLE_PRIVATE_KEY  # Full key with \n line breaks
      xcode: latest
    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
        - ios/Pods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Install Dependencies
        script: |
          gem install cocoapods --user-install
          cd ios
          pod install
          cd ..

      - name: Build IPA
        script: |
          set -exo pipefail
          xcodebuild -project ios/YourProject.xcodeproj \
            -scheme "YourScheme" \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            clean archive \
            -archivePath $CM_BUILD_DIR/YourApp.xcarchive \
            CODE_SIGN_STYLE="Automatic"

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/YourApp.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key:
          key_id: $APPLE_KEY_ID         # Direct variable reference
          issuer_id: $APPLE_ISSUER_ID   # No quotes needed
          key: $APPLE_PRIVATE_KEY       # Private key content with \n
        submit_to_testflight: true

      email:
        recipients:
          - saifulloh.fadli@gmail.com