# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "3R76KS73QY",
      issuer_id: "e4d131c6-44fb-40f5-8bf0-aeacc347897d",
      key_filepath: "./fastlane/AuthKey_3R76KS73QY.p8",
      duration: 1200,
      in_house: false # optional but may be required if using match/sigh
    )
    increment_build_number(xcodeproj: "UIkitZeroToHero.xcodeproj")
    build_app(
      scheme: "UIkitZeroToHero",
      export_options: {
        provisioningProfiles: {
          "calterras.com.UIkitZeroToHero" => "OctoPals-Distribution-Provisioning-Profiles"
          }
        }
    )

    pilot(api_key: api_key)
  end
end
